### ISSUE TITLE
Information page content needs to be updated as per plugin.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [wpswings/membership-for-woocommerce#108]
WordPress version: 5.8.2
WooCommerce version: 5.9
Version: 2.0.1
Description: Information page content needs to be updated as per plugin.
![Screenshot (55)](https://user-images.githubusercontent.com/76723329/144056161-1029ab3d-e31e-4489-ac16-b9e1e2fbf987.png)
![Screenshot (54)](https://user-images.githubusercontent.com/76723329/144056188-588fb61e-3d18-4856-a898-691ff3cf7937.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Still left.

**Comment by Ananya-Cedcoss** [comment]
fixed in plugin peding by sanjeev sir for website update

**Comment by navneet-cedcoss** [comment]
Fixed
