### ISSUE TITLE
% in short description of cart amount

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/membership-for-woocommerce#115]
os: window11
wp: 5.8.2
wc: 5.9.0
version:2.0.1
description: no % should be there.
![image](https://user-images.githubusercontent.com/86113814/145595670-4f84a19d-e004-4574-89f1-8a41c66c6805.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
