### ISSUE TITLE
issue with the state details in edit membership detail

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/membership-for-woocommerce#116]
os: windiw11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: members> edit member
description: state detail is not appropriate.
![image](https://user-images.githubusercontent.com/86113814/145596052-9db265ca-58a0-4440-aa24-939ce28add20.png)

**Comment by rishabhmwb** [comment]
fixed
