### ISSUE TITLE
issue with the membership price(round off)

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/membership-for-woocommerce#117]
os: windiw11
wp: 5.8..2
wc: 5.9.0
version: 2.0.1
description: if we set 59.39, then it show 59 in membership plan page and when we buy also become 59.
![image](https://user-images.githubusercontent.com/86113814/145596542-d931e902-2d1f-429d-a2df-962b9a4727af.png)
![image](https://user-images.githubusercontent.com/86113814/145596726-f20b2c31-0cb4-41ce-8318-7994c93486d7.png)

2. discount on cart price.
![image](https://user-images.githubusercontent.com/86113814/145596800-4433908b-afe3-4668-8977-5db78ea437ef.png)

![image](https://user-images.githubusercontent.com/86113814/145596831-135db709-6e40-4f33-bb14-00016adbd50b.png)

**Comment by ashish-wps** [comment]
Fixed
