### ISSUE TITLE
Issue with the quantity of offer in Membership details

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/membership-for-woocommerce#118]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: membership history
description: it show 'x' without any quantity. 
![image](https://user-images.githubusercontent.com/86113814/145597126-8ade14d0-4ffa-4fe1-928c-1bbbb1b2e0df.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
