### ISSUE TITLE
Issue with the redirect link in membership offer  in membership details. 

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/membership-for-woocommerce#119]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: membership history
description: no redirect link on membership offer product.
![image](https://user-images.githubusercontent.com/86113814/145597427-6f2a5fde-9994-4fcb-acfd-4d10b6a96a5c.png)

**Comment by rishabhmwb** [comment]
its not a product

**Comment by ashish-wps** [comment]
Okay
