### ISSUE TITLE
Access type details shown in plan type 

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/membership-for-woocommerce#120]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: edit member
description: detail of access type is shown in plan type in edit member.

![image](https://user-images.githubusercontent.com/86113814/145597923-8dd1dbee-5f56-40bc-abc0-410705367eef.png)

![image](https://user-images.githubusercontent.com/86113814/145597875-29df6697-1c84-4d0c-80bc-e93d25a1d368.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist
