### ISSUE TITLE
Issue with the size of no thanks button after preview page in new page

### ISSUE THREAD

**Issue by prateek-cedcoss** [wpswings/membership-for-woocommerce#121]
os: window11
wp: 5.8.2
wc: 5.9.0
version: 2.0.1
path: preview page
description: when we attach shortcode in new after, then in preview page after saving it thanks button is not appropriate. 
![image](https://user-images.githubusercontent.com/86113814/145598414-2df8ce8a-3742-43f7-a7cd-894dbabb5531.png)

**Comment by rishabhmwb** [comment]
fixed
