### ISSUE TITLE
When you update the plugin. Notice is displayed.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#125]
**Bug Name -** When you update the plugin. Notice is displayed.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.0.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/156305309-fd821ffe-5791-4758-8ebf-4954e7833ebb.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
