### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#128]
**Bug Name -** Fatal Error
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.0.3
**Description -**

When any admin are using the previous version of the plugin then he/she update the plugin then this fatal error are displayed.

![image](https://user-images.githubusercontent.com/76723393/156354240-4d00240f-476b-4fa8-99bb-85f52095e364.png)

**Comment by Ananya-Cedcoss** [comment]
resolvesd

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay

**Comment by rishabhmwb** [comment]
resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
