### ISSUE TITLE
Pro notification displayed for org user.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#129]
**Bug Name -** Pro notification displayed for org user.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.0.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/160984265-91ea336b-2a10-48a7-b05e-de61687853fd.png)

**Comment by rishabhmwb** [comment]
resolved

**Comment by rishabhmwb** [comment]
resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
