### ISSUE TITLE
After clicking on links, block are created over links.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#130]
**Bug Name -** After clicking on links, block are created over links.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.0.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/160986746-595876da-20fc-4323-b27b-3e224fb6adcc.png)

**Comment by AnuraktSachan-CEDCOSS** [comment]
![image](https://user-images.githubusercontent.com/76723393/160987451-8742fab3-56a9-40f5-b82f-733ad626ddc1.png)

**Comment by rishabhmwb** [comment]
resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
