### ISSUE TITLE
Warning Notice.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#131]
**Bug Name -** Warning Notice.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.0.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/160988009-a8557328-d0ac-49f2-a377-18402ba2183d.png)

**Comment by rishabhmwb** [comment]
resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
