### ISSUE TITLE
Notice.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#133]
**Bug Name -** Notice
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.1.0
**Description -**

![image](https://user-images.githubusercontent.com/76723393/161002594-bc41b1df-183c-4feb-9bde-fe27c3ce188d.png)

**Comment by rishabhmwb** [comment]
resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
