### ISSUE TITLE
Membership is created but not applicable.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#134]
**Bug Name -** Membership is created but not applicable.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.2.1
**WordPress Version -** 5.9
**Plugin Version -** 2.1.0
**Description -**

https://www.awesomescreenshot.com/video/8159417?key=54b459f9b1c025e96cb881cd19f2cd0f

**Comment by rishabhmwb** [comment]
resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
