### ISSUE TITLE
Warning Notice

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#137]
**Bug Name -** Warning Notice
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.6.0
**WordPress Version -** 6.0.0
**Plugin Version -** 2.1.3
**Description -**

![image](https://user-images.githubusercontent.com/76723393/174278685-1f569d1d-5996-4448-b408-ca485fcb3e7a.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
