### ISSUE TITLE
For lifetime membership, expiry date are displayed.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#138]
**Bug Name -** For lifetime membership, expiry date are displayed.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.6.0
**WordPress Version -** 6.0.0
**Plugin Version -** 2.1.3
**Description -**

Under My Account in the Membership Details tab, when users want to check their membership details & they view it then this bug is detected.

![image](https://user-images.githubusercontent.com/76723393/174290944-084eb176-f0b6-4b78-b905-0d263136b944.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
