### ISSUE TITLE
PHP Malware Issue.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#139]
**Bug Name -** PHP Malware Issue.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.6.0
**WordPress Version -** 6.0.0
**Plugin Version -** 2.1.3
**Description -**

ObfuscatedPhp /home/cedcoss/Desktop/membership-for-woocommerce/includes/class-membership-checkout-validation.php
0x1dbe:$concat_with_spaces: $pcexp[2] = '/^(' . $alpha1 . '{1}' . $alpha2 . '[0-9]{1}' . $alpha4 . ')([0-9]{1}' . $alpha5 . 

ObfuscatedPhp /home/cedcoss/Desktop/membership-for-woocommerce/public/class-membership-for-woocommerce-public.php
0x1573:$concat_with_spaces: $client_id . '&currency=' . $currency . '&intent=' . $intent . '&components=' . $component . '&disable-funding=' . $disable_fund . '&vault=' . $vault . '&debug=' . 
0x158f:$concat_with_spaces: $currency . '&intent=' . $intent . '&components=' . $component . '&disable-funding=' . $disable_fund . '&vault=' . $vault . '&debug=' .

**Comment by rishabhmwb** [comment]
resolved

**Comment by AnuraktSachan-CEDCOSS** [comment]
Fixed but new found.

ObfuscatedPhp /home/cedcoss/Desktop/membership-for-woocommerce/public/class-membership-for-woocommerce-public.php
0x1573:$concat_with_spaces: $client_id . '&currency=' . $currency . '&intent=' . $intent . '&components=' . $component . '&disable-funding=' . $disable_fund . '&vault=' . $vault . '&debug=' . 
0x158f:$concat_with_spaces: $currency . '&intent=' . $intent . '&components=' . $component . '&disable-funding=' . $disable_fund . '&vault=' . $vault . '&debug=' .

**Comment by rishabhmwb** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
