### ISSUE TITLE
PHPcs Issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [wpswings/membership-for-woocommerce#140]
**Bug Name -** PHPcs Issues
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.6.0
**WordPress Version -** 6.0.0
**Plugin Version -** 2.1.3
**Description -**

[membership-for-woocommerce.docx](https://github.com/wpswings/membership-for-woocommerce/files/8941969/membership-for-woocommerce.docx)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by AnuraktSachan-CEDCOSS** [comment]
Okay
