### ISSUE TITLE
Membership cancel option is not available.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#142]
Woo Commerce Version - 6.8.2
WordPress Version - 6.0.1
Plugin Version - 2.1.4
Description - Membership cancel option is not available

Steps - 
1. Go to to the WP Swings > Membership For WooCommerce
2. Enable the plugin and Enable the membership cancel option.
3. Go to shop page and purchase a membership plan.
4. Go to the odrder page and complete the process.
5. Go to the site > My Account
6. Verify the result.

![My account – Membership For WooCommerce](https://user-images.githubusercontent.com/105413021/186865729-a2d2f7aa-fb4b-4029-b951-eb86bad75aba.png)

**Comment by rishabhmwb** [comment]
you will get cancel button in membership details tab

**Comment by ashish-wps** [comment]
okay
