### ISSUE TITLE
QA phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#143]
**Woo Commerce Version** - 6.8.2
**WordPress Version** - 6.0.1
**Plugin Version** - 2.1.4
**Description** - WC and WP version is not updated

PHPcs Issues

https://drive.google.com/drive/folders/1wARZN4EIKV_ART77ZzzSnG7W2qsIe9uj?usp=sharing

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
