### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#146]
**Wordpress**: 6.1.1
**WooCommerce** : 7.3.0
**version**: 2.1.8
**Description** : Security Issue

![image](https://user-images.githubusercontent.com/105413021/216509033-34e84ddb-f02f-4893-8790-a7ab3d18f3a6.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Okay
