### ISSUE TITLE
phpcs Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#147]
**Wordpress** : 6.1.1
**WooCommerce** : 7.3.0
**version** : 2.1.8
**Description** : phpcs Issue

[PHPcs.docx](https://github.com/wpswings/membership-for-woocommerce/files/10575408/PHPcs.docx)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed

[PHPcs.docx](https://github.com/wpswings/membership-for-woocommerce/files/10661671/PHPcs.docx)
