### ISSUE TITLE
Show error when user buy discount product

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#148]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin Version** - 2.2.0
**Description** - Show error when user buy discount product

![Screenshot at 2023-03-07 15-06-31](https://user-images.githubusercontent.com/105413021/223394404-760bebd6-d7f0-4d0b-bb3e-236117b4d3cc.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
