### ISSUE TITLE
Show error when user register plan with Membership Registration Shortcodes

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#149]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin Version** - 2.2.0
**Description** - Show error when user register plan with Membership Registration Shortcodes

[screencapture-localhost-10033-registration-2023-03-07-15_44_27.pdf](https://github.com/wpswings/membership-for-woocommerce/files/10908407/screencapture-localhost-10033-registration-2023-03-07-15_44_27.pdf)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
