### ISSUE TITLE
Show Red Highlight on binary price but membership created

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#150]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin Version** - 2.2.0
**Description** - Show Red Highlight on binary price but membership created

https://user-images.githubusercontent.com/105413021/223424916-6c9a36b9-4928-42af-8715-5d373da54625.mp4

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
