### ISSUE TITLE
phpcs Issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#151]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin Version** - 2.2.0
**Description** - phpcs issues

[PHPcs.docx](https://github.com/wpswings/membership-for-woocommerce/files/10909589/PHPcs.docx)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
