### ISSUE TITLE
Same content for both settings

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#152]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin Version** - 2.2.0
**Description** - Same content for both settings

![image](https://user-images.githubusercontent.com/105413021/224617004-e915bb66-b6f9-4688-8be1-848d91da299d.png)

**Comment by rishabhmwb** [comment]
not an issue , two pages may have same title

**Comment by ashish-wps** [comment]
okay
