### ISSUE TITLE
Show error in Membership Setting > Add Member

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#153]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin Version** - 2.2.0
**Description** - Show error in Membership Setting > Add Member

![image](https://user-images.githubusercontent.com/105413021/224622473-4efec3fc-52d0-40c2-a979-433d790f1eca.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
![image](https://user-images.githubusercontent.com/105413021/225610778-1a35912b-9b04-4b7d-acd4-d6b9fd5098aa.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
