### ISSUE TITLE
Membership plugin does not work with Decimal

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#154]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin Version** - 2.2.0
**Description** - Membership plugin does not work with Decimal
**Step** -
1. Create a membership plan.
2. Go to the Membership Setting > Purchase discount offer
3. Select discount type Discount type " Percentage "
4. Enter discount 20, It's mean 20% discount on product.
5. Verify the result.
6. If product price is 18 rs, so after 20% discount product price is 14.4 but it's shows 14 rs.

![image](https://user-images.githubusercontent.com/105413021/224635609-361f0b99-9a3c-4d15-a8ae-5a5869d1f241.png)

![image](https://user-images.githubusercontent.com/105413021/224636048-0d219cfe-e7e8-4671-8bdc-1278085a5ab9.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
![image](https://user-images.githubusercontent.com/105413021/225617543-4df8dc0e-0b8f-4a7a-8443-6e2a148dcc45.png)

**Comment by rishabhmwb** [comment]
its default functionality we will fix this in next update

**Comment by navneet-cedcoss** [comment]
It will take around value

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Okay.. Verified
