### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#155]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin Version** - 2.2.0
**Description** - Language Issue

![image](https://user-images.githubusercontent.com/105413021/224651728-1c4a1d61-c20d-4d93-be26-4f803bfeaf2d.png)

![image](https://user-images.githubusercontent.com/105413021/224651920-62694676-86a1-431d-9743-baf019862a24.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
