### ISSUE TITLE
Please make other option compulsory

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#156]
**Woo Commerce Version** - 7.4.1
**WordPress Version** - 6.1.1
**Plugin Version** - 2.2.0
**Description** - Please make other option compulsory

https://user-images.githubusercontent.com/105413021/225625395-9aa2b7bc-bbaf-4866-8534-29a6341a720f.mp4

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
