### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#157]
**Woo Commerce Version** - 7.6.0
**WordPress Version** - 6.2
**Plugin Version** - 2.2.1
**Description** - Design Issue

![image](https://user-images.githubusercontent.com/105413021/233282986-74f93cb7-cbd1-4a28-af55-44e56321ef40.png)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
