### ISSUE TITLE
phpcs issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#159]
Woo Commerce Version - 7.6.1
WordPress Version - 6.2
Plugin Version - 2.2.2
Description - phpcs issue

[PHPcs.docx](https://github.com/wpswings/membership-for-woocommerce/files/11421716/PHPcs.docx)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
