### ISSUE TITLE
QA issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#160]
Woo Commerce Version - 7.6.1
WordPress Version - 6.2
Plugin Version - 2.2.2
Description - QA issue ( Plugin Version is not updated on line 254)

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/09b2069c-f848-4641-99c1-79e05610770c)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
