### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#162]
**Woo Commerce Version** - 7.9.0
**WordPress Version** - 6.2.2
**Plugin Version** - 2.3.1
**Description** - Language Issue

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/9ac659de-6925-41dd-b681-b9e8716878a5)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
