### ISSUE TITLE
It's show Fatal Error when user create member from Membership Setting > Add Member

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#163]
**Woo Commerce Version** - 8.1.0
**WordPress Version** - 6.3.1
**Plugin Version** - 2.3.2
**Description** - It's show Fatal Error when user create member from Membership Setting > Add Member

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/fc1de3dd-aee2-4d03-b55e-d2a848d77b11)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
