### ISSUE TITLE
 It's shows membership order which are not place by admin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#164]
**Woo Commerce Version** - 8.1.0
**WordPress Version** - 6.3.1
**Plugin Version** - 2.3.2
**Description** - It's shows membership order which are not place by admin

https://github.com/wpswings/membership-for-woocommerce/assets/105413021/a3e7f093-d691-4d24-9e38-afc74323c564

**Comment by rishabhmwb** [comment]
I can clearly see that you are not selected the plan while creating member

**Comment by ashish-wps** [comment]
Fixed
