### ISSUE TITLE
Admin can create membership plan with inappropriate Set Access Type ( Duration )

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#165]
**Woo Commerce Version** - 8.1.0
**WordPress Version** - 6.3.1
**Plugin Version** - 2.3.2
**Description** - Admin can create membership plan with inappropriate Set Access Type ( Duration )

https://github.com/wpswings/membership-for-woocommerce/assets/105413021/0eeee6b3-dac9-43aa-bf94-6e9688f82770

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
