### ISSUE TITLE
When admin enter decimal number than it's border turn red but admin able to create plan

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#166]
**Woo Commerce Version** - 8.1.0
**WordPress Version** - 6.3.1
**Plugin Version** - 2.3.2
**Description** - When admin enter decimal number than it's border turn red but admin able to create plan.

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/f1e9797a-b530-45f7-9c61-10b96ca8c7ce)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
