### ISSUE TITLE
Discount on Cart is not showing same detail on Membership detail

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#167]
**Woo Commerce Version** - 8.1.0
**WordPress Version** - 6.3.1
**Plugin Version** - 2.3.2
**Description** - Discount on Cart is not showing same detail on Membership detail

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/4469a97a-8ea9-4bc8-909c-6c47dd06ba27)

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/aa7aa1ca-c5f4-4a3a-84b8-b437e86d2c44)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
