### ISSUE TITLE
User able enter negative value in multi step form 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#168]
**Woo Commerce Version** - 8.2.1
**WordPress Version** - 6.3.2
**Plugin Version** - 2.3.3
**Description** - User able enter negative value in multi step form 

[scrnli_25_10_2023_17-10-03.webm](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/e0e91712-4b94-4bee-bd4d-54ec32c65793)

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/a1c0d796-2fc3-45a8-849a-eb23e1d04a0e)

**Comment by rishabhmwb** [comment]
fixed

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
