### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#171]
**Woo Commerce Version** - 8.2.1
**WordPress Version** - 6.3.2
**Plugin Version** - 2.3.3
**Description** - Design issue

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/34147218-7597-4c8b-8d48-abe7309ea870)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
