### ISSUE TITLE
Membership discount issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#172]
**Woo Commerce Version - 8.2.1
WordPress Version - 6.3.2
Plugin Version - 2.3.3
Description -** Membership discount issue
**Note**- It should give discount on subtotal, not on shipping.

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/0e810298-df0f-49e3-b92b-d16d097bb496)

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/c807c664-6aaa-42dd-9043-a49716e790ce)

**Comment by navneet-cedcoss** [comment]
issues fixed
https://www.awesomescreenshot.com/video/23185987?key=7bde449fe380daf35b61628725b36601

**Comment by ashish-wps** [comment]
Fixed
