### ISSUE TITLE
Fatal Error when admin cancel membership

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#174]
**Woo Commerce Version - 8.5.1
WordPress Version - 6.4.2
Plugin Version - 2.3.5
Description -** Fatal Error when admin cancel membership

[scrnli_19_01_2024_10-49-57.webm](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/2d35b9a5-34be-4812-a02f-11db289b3711)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
