### ISSUE TITLE
Add validation on Add Member > Phone Setting

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#176]
**Woo Commerce Version - 9.0.0
WordPress Version - 6.5.4
Plugin Version - 2.5.1
Description -** It should working as phone number section with country code, not as number field.

- Validation on mobile no.

- Add county code

- Remove drop-down

![image](https://github.com/wpswings/membership-for-woocommerce/assets/105413021/870488c6-dd1b-4b67-97db-8f88520615f9)

**Comment by navneet-cedcoss** [comment]
Remove drop-down - Implemented
Validation on mobile no. - done
Add county code - we follow the woocommerce standard ,please refer to this video
https://www.awesomescreenshot.com/video/28801751?key=0b557f7bd7526b7edbbca1180fa9eea9

**Comment by ashish-wps** [comment]
Fixed
