### ISSUE TITLE
Total Discount Benefits should show 0, when user did not get any discount benefit 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#178]
**Woo Commerce Version - 9.4.2
WordPress Version - 6.7
Plugin Version - 2.6.2
Description -** Total Discount Benefits should show 0, when user did not get any discount benefit 

![image](https://github.com/user-attachments/assets/39e99b34-ea1f-44dd-9975-ce1a2511c7e0)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
