### ISSUE TITLE
phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#180]
**Woo Commerce Version - 9.4.2
WordPress Version - 6.7
Plugin Version - 2.6.2
Description -** phpcs issues

ORG- 
[PHPcs.docx](https://github.com/user-attachments/files/17826688/PHPcs.docx)

PRO-
[PHPcs.docx](https://github.com/user-attachments/files/17826694/PHPcs.docx)

**Comment by navneet-cedcoss** [comment]
Few issues are not fixed rest all issues are fixed

**Comment by ashish-wps** [comment]
okay
