### ISSUE TITLE
Warning message shown when user place a membership product with Sign fee and free trial

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#181]
**Woo Commerce Version - 9.4.2
WordPress Version - 6.7.1
Plugin Version - 2.6.2
Description -**  Warning message shown when user place a membership product with Sign fee and free trial

![image](https://github.com/user-attachments/assets/7f2e613f-905d-45e8-b5ca-9fc5e22c9036)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
okay
