### ISSUE TITLE
Sign-up fee and free trial remain active even after disabling the Free Trial settings.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/membership-for-woocommerce#183]
**Woo Commerce Version - 9.4.2
WordPress Version - 6.7.1
Plugin Version - 2.6.2
Description -**  Sign-up fee and free trial remain active even after disabling the Free Trial settings.

[scrnli_pw6HEkuh7bqb15.webm](https://github.com/user-attachments/assets/0b7306f0-02d8-433b-a839-8b176cb31c8b)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
